In [1]:
import modern_robotics as mr

In [2]:
dir(mr)

['Adjoint',
 'AxisAng3',
 'AxisAng6',
 'CartesianTrajectory',
 'ComputedTorque',
 'CubicTimeScaling',
 'DistanceToSE3',
 'DistanceToSO3',
 'EndEffectorForces',
 'EulerStep',
 'FKinBody',
 'FKinSpace',
 'ForwardDynamics',
 'ForwardDynamicsTrajectory',
 'GravityForces',
 'IKinBody',
 'IKinSpace',
 'InverseDynamics',
 'InverseDynamicsTrajectory',
 'JacobianBody',
 'JacobianSpace',
 'JointTrajectory',
 'MassMatrix',
 'MatrixExp3',
 'MatrixExp6',
 'MatrixLog3',
 'MatrixLog6',
 'NearZero',
 'Normalize',
 'ProjectToSE3',
 'ProjectToSO3',
 'QuinticTimeScaling',
 'RotInv',
 'RpToTrans',
 'ScrewToAxis',
 'ScrewTrajectory',
 'SimulateControl',
 'TestIfSE3',
 'TestIfSO3',
 'TransInv',
 'TransToRp',
 'VecTose3',
 'VecToso3',
 'VelQuadraticForces',
 '__builtins__',
 '__cached__',
 '__doc__',
 '__file__',
 '__loader__',
 '__name__',
 '__package__',
 '__path__',
 '__spec__',
 '__version__',
 'ad',
 'core',
 'np',
 'print_function',
 'se3ToVec',
 'so3ToVec']

In [3]:
# unit rotation axis
omega_hat = mr.np.array([0,0,1]) 
theta = mr.np.pi/4
# 3-vector form  of rotation angle
omega = omega_hat*theta 
omega

array([0.        , 0.        , 0.78539816])

In [4]:
help(mr.AxisAng3)

Help on function AxisAng3 in module modern_robotics.core:

AxisAng3(expc3)
    Converts a 3-vector of exponential coordinates for rotation into
    axis-angle form
    
    :param expc3: A 3-vector of exponential coordinates for rotation
    :return omghat: A unit rotation axis
    :return theta: The corresponding rotation angle
    
    Example Input:
        expc3 = np.array([1, 2, 3])
    Output:
        (np.array([0.26726124, 0.53452248, 0.80178373]), 3.7416573867739413)



In [5]:
# get Unit axis of Rotation and theta from 3-vector of exponential coordinates 
mr.AxisAng3(omega) 

(array([0., 0., 1.]), 0.7853981633974483)

In [6]:
help(mr.AxisAng3)

Help on function AxisAng3 in module modern_robotics.core:

AxisAng3(expc3)
    Converts a 3-vector of exponential coordinates for rotation into
    axis-angle form
    
    :param expc3: A 3-vector of exponential coordinates for rotation
    :return omghat: A unit rotation axis
    :return theta: The corresponding rotation angle
    
    Example Input:
        expc3 = np.array([1, 2, 3])
    Output:
        (np.array([0.26726124, 0.53452248, 0.80178373]), 3.7416573867739413)



In [7]:
# get so3(skew-symmetric matrix) from 3-vector of exponential coordinates 
so3 = mr.VecToso3(omega)
so3

array([[ 0.        , -0.78539816,  0.        ],
       [ 0.78539816,  0.        , -0.        ],
       [-0.        ,  0.        ,  0.        ]])

In [8]:
# get 3-vector of exponential coordinates from so3(skew-symmetric matrix)
omega = mr.so3ToVec(so3)
omega

array([0.        , 0.        , 0.78539816])

In [9]:
# get SO3(Rotation matrix) from so3(skew-symmetric matrix)
R = mr.MatrixExp3(so3)
R

array([[ 0.70710678, -0.70710678,  0.        ],
       [ 0.70710678,  0.70710678,  0.        ],
       [ 0.        ,  0.        ,  1.        ]])

In [10]:
# get so3(skew-symmetric matrix) from SO3(Rotation matrix)
so3 = mr.MatrixLog3(R)
so3

array([[ 0.        , -0.78539816,  0.        ],
       [ 0.78539816,  0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        ]])

In [11]:
# 6-vector form twist, V 
V = mr.np.array([1,0,0,1,2,3])
V

array([1, 0, 0, 1, 2, 3])

In [12]:
# get se3(twist 4x4 matrix) from 6-vector spatial velocity, V
se3 = mr.VecTose3(V)
se3

array([[ 0.,  0.,  0.,  1.],
       [ 0.,  0., -1.,  2.],
       [ 0.,  1.,  0.,  3.],
       [ 0.,  0.,  0.,  0.]])

In [13]:
S, theta_dot = mr.AxisAng6(V)
S, theta_dot

(array([1., 0., 0., 1., 2., 3.]), 1.0)

In [14]:
# get 6-vector spatial velocity, V from se3(twist 4x4 matrix)
V = mr.se3ToVec(se3)
V

array([1., 0., 0., 1., 2., 3.])

In [15]:
# get Homogeneous Transformation matrix T from se3(twist 4x4 matrix)
T = mr.MatrixExp6(se3)
T

array([[ 1.        ,  0.        ,  0.        ,  1.        ],
       [ 0.        ,  0.54030231, -0.84147098,  0.30384889],
       [ 0.        ,  0.84147098,  0.54030231,  3.44380834],
       [ 0.        ,  0.        ,  0.        ,  1.        ]])

In [16]:
# get se3(twist 4x4 matrix) from Homogeneous Transformation matrix, T
se3 = mr.MatrixLog6(T)
se3

array([[ 0.,  0.,  0.,  1.],
       [ 0.,  0., -1.,  2.],
       [ 0.,  1.,  0.,  3.],
       [ 0.,  0.,  0.,  0.]])

In [17]:
V = mr.se3ToVec(se3)
V

array([1., 0., 0., 1., 2., 3.])