In [2]:
import symbolic_modern_robotics as smr

In [3]:
help(smr)

Help on module symbolic_modern_robotics:

NAME
    symbolic_modern_robotics

DESCRIPTION
    # Modern Robotics Python Symbolic Calculation Library, BSD License.
    # Written by Dongil Choi, MyongJi University, South Korea. dongilc@mju.ac.kr
    # Theoretical Background (Textbook) : Modern Robotics, Kevin M. Lynch and Frank C. Park
    # Symbolic Calculation Functions : Skew Symmatric
    # 2021 / 04 / 05
    # How to use : 
    #       import intelligent_robotics as ir
    #       dir(ir)
    #       help(ir.DH)

FUNCTIONS
    AxisAng3(w)
        ###### Rotation Matrix
        # Calculate unit axis of rotation(omega_hat) and theta from 3-vector
    
    AxisAng6(V)
        ###### Homogeneous Transform Matrix
        # Calculate screw-axis and angle from 6-vector
    
    MatrixExp3(so3mat)
        ###### Rotation Matrix
        # Calculate SO3 from so3 by Matrix exponential
    
    MatrixExp6(se3mat)
        ###### Homogeneous Transform Matrix
        # Calculate SE3 from se3 by Matr

In [4]:
import sympy as s

In [8]:
T_hf = s.Matrix([[1, 0, 0, -0.1],
                 [0, 1, 0, 0],
                 [0, 0, 1, 0],
                 [0, 0, 0, 1]])
T_hf

Matrix([
[1, 0, 0, -0.1],
[0, 1, 0,    0],
[0, 0, 1,    0],
[0, 0, 0,    1]])

In [9]:
T_af = s.Matrix([[1, 0, 0, -0.25],
                 [0, 0, 1, 0],
                 [0, 1, 0, 0],
                 [0, 0, 0, 1]])
T_af

Matrix([
[1, 0, 0, -0.25],
[0, 0, 1,     0],
[0, 1, 0,     0],
[0, 0, 0,     1]])

In [14]:
import modern_robotics as mr
import numpy as np

In [12]:
dir(mr)

['Adjoint',
 'AxisAng3',
 'AxisAng6',
 'CartesianTrajectory',
 'ComputedTorque',
 'CubicTimeScaling',
 'DistanceToSE3',
 'DistanceToSO3',
 'EndEffectorForces',
 'EulerStep',
 'FKinBody',
 'FKinSpace',
 'ForwardDynamics',
 'ForwardDynamicsTrajectory',
 'GravityForces',
 'IKinBody',
 'IKinSpace',
 'InverseDynamics',
 'InverseDynamicsTrajectory',
 'JacobianBody',
 'JacobianSpace',
 'JointTrajectory',
 'MassMatrix',
 'MatrixExp3',
 'MatrixExp6',
 'MatrixLog3',
 'MatrixLog6',
 'NearZero',
 'Normalize',
 'ProjectToSE3',
 'ProjectToSO3',
 'QuinticTimeScaling',
 'RotInv',
 'RpToTrans',
 'ScrewToAxis',
 'ScrewTrajectory',
 'SimulateControl',
 'TestIfSE3',
 'TestIfSO3',
 'TransInv',
 'TransToRp',
 'VecTose3',
 'VecToso3',
 'VelQuadraticForces',
 '__builtins__',
 '__cached__',
 '__doc__',
 '__file__',
 '__loader__',
 '__name__',
 '__package__',
 '__path__',
 '__spec__',
 '__version__',
 'ad',
 'core',
 'np',
 'print_function',
 'se3ToVec',
 'so3ToVec']

In [66]:
help(mr.TransInv)

Help on function TransInv in module modern_robotics.core:

TransInv(T)
    Inverts a homogeneous transformation matrix
    
    :param T: A homogeneous transformation matrix
    :return: The inverse of T
    Uses the structure of transformation matrices to avoid taking a matrix
    inverse, for efficiency.
    
    Example input:
        T = np.array([[1, 0,  0, 0],
                      [0, 0, -1, 0],
                      [0, 1,  0, 3],
                      [0, 0,  0, 1]])
    Output:
        np.array([[1,  0, 0,  0],
                  [0,  0, 1, -3],
                  [0, -1, 0,  0],
                  [0,  0, 0,  1]])



In [ ]:
# Example 3.28

In [148]:
T_hf = np.array([[1, 0, 0, -0.1],
                 [0, 1, 0, 0],
                 [0, 0, 1, 0],
                 [0, 0, 0, 1]])
T_hf

array([[ 1. ,  0. ,  0. , -0.1],
       [ 0. ,  1. ,  0. ,  0. ],
       [ 0. ,  0. ,  1. ,  0. ],
       [ 0. ,  0. ,  0. ,  1. ]])

In [149]:
T_af = np.array([[1, 0, 0, -0.25],
                 [0, 0, 1, 0],
                 [0, -1, 0, 0],
                 [0, 0, 0, 1]])
T_af

array([[ 1.  ,  0.  ,  0.  , -0.25],
       [ 0.  ,  0.  ,  1.  ,  0.  ],
       [ 0.  , -1.  ,  0.  ,  0.  ],
       [ 0.  ,  0.  ,  0.  ,  1.  ]])

In [150]:
Ad_T_hf = mr.Adjoint(T_hf)
Ad_T_hf

array([[ 1. ,  0. ,  0. ,  0. ,  0. ,  0. ],
       [ 0. ,  1. ,  0. ,  0. ,  0. ,  0. ],
       [ 0. ,  0. ,  1. ,  0. ,  0. ,  0. ],
       [ 0. ,  0. ,  0. ,  1. ,  0. ,  0. ],
       [ 0. ,  0. ,  0.1,  0. ,  1. ,  0. ],
       [ 0. , -0.1,  0. ,  0. ,  0. ,  1. ]])

In [151]:
Ad_T_af = mr.Adjoint(T_af)
Ad_T_af

array([[ 1.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ],
       [ 0.  ,  0.  ,  1.  ,  0.  ,  0.  ,  0.  ],
       [ 0.  , -1.  ,  0.  ,  0.  ,  0.  ,  0.  ],
       [ 0.  ,  0.  ,  0.  ,  1.  ,  0.  ,  0.  ],
       [ 0.  , -0.25,  0.  ,  0.  ,  0.  ,  1.  ],
       [ 0.  ,  0.  , -0.25,  0.  , -1.  ,  0.  ]])

In [152]:
F_h = np.array([0,0,0,0,-5,0])
F_h

array([ 0,  0,  0,  0, -5,  0])

In [153]:
F_a = np.array([0,0,0,0,0,1])
F_a

array([0, 0, 0, 0, 0, 1])

In [154]:
Ad_T_hf.T@F_h + Ad_T_af.T@F_a

array([ 0.  ,  0.  , -0.75,  0.  , -6.  ,  0.  ])

In [155]:
# Example 3.23

In [156]:
T_sb = np.array([[-1, 0, 0, 4],
                 [0, 1, 0, 0.4],
                 [0, 0, -1, 0],
                 [0, 0, 0, 1]])
T_sb

array([[-1. ,  0. ,  0. ,  4. ],
       [ 0. ,  1. ,  0. ,  0.4],
       [ 0. ,  0. , -1. ,  0. ],
       [ 0. ,  0. ,  0. ,  1. ]])

In [158]:
V_b = np.array([0,0,-2,2.8,4,0])
V_b

array([ 0. ,  0. , -2. ,  2.8,  4. ,  0. ])

In [159]:
mr.Adjoint(T_sb)@V_b

array([ 0.,  0.,  2., -2., -4.,  0.])

In [160]:
# Example 3.26

In [161]:
help(np.cos)

Help on ufunc object:

cos = class ufunc(builtins.object)
 |  Functions that operate element by element on whole arrays.
 |  
 |  To see the documentation for a specific ufunc, use `info`.  For
 |  example, ``np.info(np.sin)``.  Because ufuncs are written in C
 |  (for speed) and linked into Python with NumPy's ufunc facility,
 |  Python's help() function finds this page whenever help() is called
 |  on a ufunc.
 |  
 |  A detailed explanation of ufuncs can be found in the docs for :ref:`ufuncs`.
 |  
 |  Calling ufuncs:
 |  ===============
 |  
 |  op(*x[, out], where=True, **kwargs)
 |  Apply `op` to the arguments `*x` elementwise, broadcasting the arguments.
 |  
 |  The broadcasting rules are:
 |  
 |  * Dimensions of length 1 may be prepended to either array.
 |  * Arrays may be repeated along dimensions of length 1.
 |  
 |  Parameters
 |  ----------
 |  *x : array_like
 |      Input arrays.
 |  out : ndarray, None, or tuple of ndarray and None, optional
 |      Alternate array o

In [162]:
T_sb = np.array([[np.cos(30*np.pi/180.), -np.sin(30*np.pi/180.), 0, 1],
                 [np.sin(30*np.pi/180.), np.cos(30*np.pi/180.), 0, 2],
                 [0, 0, 1, 0],
                 [0, 0, 0, 1]])
T_sb

array([[ 0.8660254, -0.5      ,  0.       ,  1.       ],
       [ 0.5      ,  0.8660254,  0.       ,  2.       ],
       [ 0.       ,  0.       ,  1.       ,  0.       ],
       [ 0.       ,  0.       ,  0.       ,  1.       ]])

In [163]:
T_sc = np.array([[np.cos(60*np.pi/180.), -np.sin(60*np.pi/180.), 0, 2],
                 [np.sin(60*np.pi/180.), np.cos(60*np.pi/180.), 0, 1],
                 [0, 0, 1, 0],
                 [0, 0, 0, 1]])
T_sc

array([[ 0.5      , -0.8660254,  0.       ,  2.       ],
       [ 0.8660254,  0.5      ,  0.       ,  1.       ],
       [ 0.       ,  0.       ,  1.       ,  0.       ],
       [ 0.       ,  0.       ,  0.       ,  1.       ]])

In [167]:
T = T_sc@mr.TransInv(T_sb)

In [168]:
help(mr.MatrixLog6)

Help on function MatrixLog6 in module modern_robotics.core:

MatrixLog6(T)
    Computes the matrix logarithm of a homogeneous transformation matrix
    
    :param R: A matrix in SE3
    :return: The matrix logarithm of R
    
    Example Input:
        T = np.array([[1, 0,  0, 0],
                      [0, 0, -1, 0],
                      [0, 1,  0, 3],
                      [0, 0,  0, 1]])
    Output:
        np.array([[0,          0,           0,           0]
                  [0,          0, -1.57079633,  2.35619449]
                  [0, 1.57079633,           0,  2.35619449]
                  [0,          0,           0,           0]])



In [174]:
se3mat = mr.MatrixLog6(T)
se3mat

array([[ 0.        , -0.52359878,  0.        ,  1.76244678],
       [ 0.52359878,  0.        ,  0.        , -1.76244678],
       [ 0.        ,  0.        ,  0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        ,  0.        ]])

In [175]:
help(mr.AxisAng6)

Help on function AxisAng6 in module modern_robotics.core:

AxisAng6(expc6)
    Converts a 6-vector of exponential coordinates into screw axis-angle
    form
    
    :param expc6: A 6-vector of exponential coordinates for rigid-body motion
                  S*theta
    :return S: The corresponding normalized screw axis
    :return theta: The distance traveled along/about S
    
    Example Input:
        expc6 = np.array([1, 0, 0, 1, 2, 3])
    Output:
        (np.array([1.0, 0.0, 0.0, 1.0, 2.0, 3.0]), 1.0)



In [179]:
V = mr.se3ToVec(se3mat)
V

array([ 0.        ,  0.        ,  0.52359878,  1.76244678, -1.76244678,
        0.        ])

In [180]:
mr.AxisAng6(V)

(array([ 0.       ,  0.       ,  1.       ,  3.3660254, -3.3660254,
         0.       ]),
 0.5235987755982988)

In [181]:
np.pi/6

0.5235987755982988